import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import Services from '../components/Services'
import Testimonial from '../components/Testimonial'
import { data } from '../data'

const Intro = dynamic(
  () => import('../components/Intro'),
  { ssr: false }
)

export default function Home({ services }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Intro />
      <Services services={services}/>
      <Testimonial />
    </div>
  )
}

export const getStaticProps = async() => {
  const services = await data;
  return {
    props: {services}
  }
}
